---
title: "p8105_hw1_jck2183"
author: "jck2183_Chia-wen Kao"
date: "2020/9/15"
output: github_document
---
My Solution to HW1
```{r}
library(tidyverse)
```
Problem 1

Create Data Frame with specified elements

```{r}
# 1.a random sample of size 10 from a standard Normal distribution
r_norm <- rnorm(10)
    #r_norm
# 2.a logical vector indicating whether elements of the sample are greater than 0
v_logical <- r_norm > 0
    #v_logical
# 3.a character vector of length 10
v_character <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
    #class(v_character)
    #length(v_character)
# 4. a factor vector of length 10, with 3 different factor "levels".
v_factor <- factor(c("S", "M", "M", "S", "L", "L", "S", "L", "M", "M"), levels = c("S", "M", "L"))

    #v_factor
    #class(v_factor)

problem1_df <- tibble(
    r_norm, 
    v_logical,
    v_character, 
    v_factor
)

pull(problem1_df, r_norm)
pull(problem1_df, v_logical)
pull(problem1_df, v_character)
pull(problem1_df, v_factor)
## Try to take the mean of each variable in your dataframe. What works and what doesn’t?

mean(r_norm) 
# r_norm variable, contains only numerics, works, and the mean is 0.3043041.
mean(v_character) 
#v_character, the charatcter variable doesn't work.
mean(v_logical) 
#v_logical works, and the result is 0.7.
mean(v_factor) 
#v_factor, the charatcter variable doesn't work
```
Problem1 2nd Chunk

Convert variable features. 

```{r}
# 1.convert the logical vector to numeric, and multiply the random sample by the result
as.numeric(v_logical) * r_norm
# 2. convert the logical vector to a factor, and multiply the random sample by the result
as.factor(v_logical) * r_norm
# The result suggests not meaningful for factors to multiply the random sample
# 3. convert the logical vector to a factor and then convert the result to numeric, and multiply the random sample by the result.
as.numeric(as.factor(v_logical)) * r_norm

## What happens, and why? Does this help explain what happens when you try to take the mean?
# Ans: Only the numeric variables can be calculated (or multiplied by) with the random sample. This also help to explain what happens when we tried to take the mean. Since only numeric variables can be calculated, including taking mean. Character / Logical variables are not available for the calculation.
```
Problem 2
```{r}
data("penguins", package = "palmerpenguins")
#1.the data in this dataset, including names / values of important variables
penguins
# 2. the size of the dataset (using nrow and ncol)
nrow(penguins)
ncol(penguins)
dim(penguins)

#3. the mean flipper length
mean(penguins$flipper_length_mm, na.rm = TRUE) 
#It would be NA if we don't deal with the missing values.By adding na.rm = TRUE syntax, we can remove the missing values and get the mean of the mean flipper length = 200.9152 mm.

## Make a scatterplot of flipper_length_mm (y) vs bill_length_mm (x); color points using the species variable (adding color = ... inside of aes in your ggplot code should help).

ggplot(data = penguins, aes(x = `bill_length_mm`, y = `flipper_length_mm`)) + geom_point(aes(color = `species`))

# Export your first scatterplot to your project directory using ggsave.

ggsave("p8105_hw1_scatterplot.pdf", height = 6, width = 6)

```